apiVersion: v2
name: gateway
version: 1.26.2-bb.0
appVersion: 1.26.2
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
  - istio
  - istiod
  - gateways
sources:
  - https://github.com/istio/istio
dependencies:
  - name: gateway
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.26.2
    alias: upstream
annotations:
  bigbang.dev/passthrough: "true"
  bigbang.dev/passthrough-toplevel-key: upstream
  bigbang.dev/maintenanceTrack: bb_integrated
  bigbang.dev/applicationVersions: |
    - Istio: 1.26.2
  helm.sh/images: |
    - name: proxyv2
      image: registry1.dso.mil/ironbank/opensource/istio/proxyv2:1.26.2
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    - [Find upstream chart's release notes and CHANGELOG here](https://istio.io/latest/news/releases)
