apiVersion: v2
name: gateway
description: Helm chart for deploying Istio gateways
type: application
version: 1.25.1-bb.1
appVersion: 1.25.1
sources:
- https://github.com/istio/istio
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
annotations:
  bigbang.dev/maintenanceTrack: bb_integrated
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    - [Find our upstream chart's CHANGELOG here](https://istio.io/latest/news/releases/1.25.x/announcing-1.25)
  helm.sh/images: | 
    - name: proxy
      image: registry1.dso.mil/ironbank/opensource/istio/proxyv2:1.25.1