apiVersion: v2
name: gateway
description: Helm chart for deploying Istio gateways
type: application
version: 1.23.2-bb.1
appVersion: 1.23.2
sources:
- https://github.com/istio/istio
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
annotations:
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    - [Find our upstream chart's CHANGELOG here](https://istio.io/latest/news/releases/1.23.2/announcing-1.23.2)
