{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ include "gateway.name" . }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "gateway.name" . }}
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    {{- range $servicePorts := .Values.defaults.service.ports }}
    - port: {{ $servicePorts.targetPort }}
      protocol: {{ $servicePorts.protocol }}
    {{- end }}
  policyTypes:
  - Ingress
{{- end }}