apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.toolkit.fluxcd.io/name: istio
    helm.toolkit.fluxcd.io/namespace: bigbang
spec:
  selector:
    app: {{ .Release.Name }}
  servers:
{{- toYaml .Values.gateway.servers | nindent 4 }}


