{{/*
Allow all egress traffic to virtual services from ingressgateway as there is no simple way of knowing all ports in advance
*/}}
{{- if and .Values.networkPolicies.enabled (not (lookup "networking.k8s.io/v1" "NetworkPolicy" "istio-gateway" "allow-virtualservice-egress")) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: allow-virtualservice-egress
  namespace: "{{ .Release.Namespace }}"
spec:
  egress:
    - to:
      - namespaceSelector: {}
  podSelector:
    matchLabels:
      istio: ingressgateway
  policyTypes:
    - Egress
{{- end }}