{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: allow-{{ .Release.Name }}-istiod-egress
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector:
    matchLabels:
      app: {{ include "gateway.name" . }}
      istio: ingressgateway
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          {{- if .Values.networkPolicies.istioNamespaceSelector }}
          app.kubernetes.io/name: {{ .Values.networkPolicies.istioNamespaceSelector.egress }}
          {{- else }}
          app.kubernetes.io/name: "istio-controlplane"
          {{- end }}
      podSelector:
        matchLabels:
          app: istiod
    ports:
    - port: 15012
      protocol: TCP
    - port: 15014
      protocol: TCP
{{- end }}
