{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: allow-{{ .Release.Name }}-virtualservice-egress
  namespace: "{{ .Release.Namespace }}"
spec:
  egress:
    - to:
      - namespaceSelector: {}
  podSelector:
    matchLabels:
      app: {{ include "gateway.name" . }}
      istio: ingressgateway
  policyTypes:
    - Egress
{{- end }}
