{{/*
Only create if it doesn't already exist in the namespace
*/}}
{{- if and .Values.networkPolicies.enabled (not (lookup "networking.k8s.io/v1" "NetworkPolicy" "istio-gateway" "default-deny")) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: default-deny
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
{{- end }}