apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-{{ .Release.Name }}-authz-policy
  namespace: istio-gateway
spec:
  action: ALLOW
  rules:
    - {}
  selector:
    matchLabels:
      istio: ingressgateway
      app: {{ include "gateway.name" . }}
